Exercise 1: Identifying Data Types

Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company’s financial reports stored in an Excel file.

ans: structured


Photographs uploaded to a social media platform.

ans: unstructured


A collection of news articles on a website.

ans: unstructured


Inventory data in a relational database.

ans: sructured


Recorded interviews from a market research study.

ans: unstructed

Exercise 2: Transformation Exercise
For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences.
ans:using Natural language processing(NLP).this can help oin extraction of some valuable data from bloct post such as structured output of variables like destination, dates etc 

Audio recordings of customer service calls.
Ans: using  Speech to Text Transcription then NLP is applied and manually extracting the impotant point.This help get the information in the form of text 

Handwritten notes from a brainstorming session.
using optical Character Recognition(OCR). This help in digitalizing hte handwritting which will intend help in grouping ideas onto spreadsheets

A video tutorial on cooking.
ans: Video Metadata extraction and Temporal Segmentation.
This help in splitting the video down  by time stamps to extract the required data

 Exercise 3 : Import a file from Kaggle

In [7]:
import pandas as pd

train_dataset = pd.read_csv(r"C:\Users\njedr\Searches\train.csv")
train_dataset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Exercise 4: Importing a CSV File

In [9]:
iris_data = pd.read_csv(r"C:\Users\njedr\Searches\IRIS_IRIS.csv")
iris_data.head()

   sepal-length  sepal-width  petal-length  petal-width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

 Exercise 5 : Export a dataframe to excel format and JSON format.
Create a simple dataframe.
Export the dataframe to an excel file.
Export the dataframe to a JSON file.

In [18]:
%pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
     ------------------------------------ 250.9/250.9 KB 513.2 kB/s eta 0:00:00
Collecting et-xmlfile
  Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe -m pip install --upgrade pip' command.

In [21]:
new_iris_data = iris_data.copy() 
new_iris_data.to_excel("new_iris_data.xlsx", index = False)
new_iris_data_excel = pd.read_excel("new_iris_data.xlsx")
new_iris_data_excel.head()

   sepal-length  sepal-width  petal-length  petal-width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [27]:
new_iris_data.to_json("new_iris_data.json", orient="records", indent=4)

Exercise 6: Reading JSON Data
Use a sample JSON dataset

Import the JSON data from the provided URL.
Use Pandas to read the JSON data.
Display the first five entries of the data.

In [26]:
new_iris_data_json = pd.read_json("new_iris_data.json")
new_iris_data_json.head()

   sepal-length  sepal-width  petal-length  petal-width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa