In [1]:
import pandas as pd
import sqlite3

In [2]:
df_flix=pd.read_csv('netflix_titles.csv')
df_flix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [3]:
df_flix.columns.tolist()

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [4]:
import sqlalchemy
engine = sqlalchemy.create_engine('sqlite:///netflix.db')
df_flix.to_sql('netflix', engine, index=False)

8807

3. Query 1: Select *

Write and execute a SQL query to select all records from the Netflix table.

In [5]:
query ='''SELECT * FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,None,None,None,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

. Query 2: Select Distinct

Write and execute a SQL query to select distinct show IDs from the Netflix table.

In [6]:
query ='''SELECT DISTINCT show_id FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

  show_id
0      s1
1      s2
2      s3
3      s4
4      s5

Query 3: Select Where

Write and execute a SQL query to select distinct titles of shows released after 2020.

In [7]:
query ='''SELECT DISTINCT title FROM netflix WHERE release_year > 2020'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                   title
0          Blood & Water
1              Ganglands
2  Jailbirds New Orleans
3           Kota Factory
4          Midnight Mass

Query 4: Select and, or, not

Write and execute a SQL query to select distinct titles of shows released after 2020 with specific conditions.

In [8]:
query ='''SELECT DISTINCT title FROM netflix WHERE release_year > 2020
AND type = 'Movie' AND listed_in = 'Dramas' '''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                   title
0                  Worth
1                Cousins
2             Fatherhood
3                Monster
4  Two Distant Strangers

Query 5: Order By

Write and execute a SQL query to select and order the titles of Netflix shows.

In [9]:
query ='''SELECT DISTINCT title FROM netflix ORDER BY title'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                           title
0                         #Alive
1  #AnneFrank - Parallel Stories
2              #FriendButMarried
3            #FriendButMarried 2
4                          #Roxy

 Query 6: Limit Values

Write and execute a SQL query to select the first 5 records from the Netflix table.

In [10]:
query ='''SELECT * FROM netflix LIMIT 5'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,None,None,None,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

 Query 7: Min, Max, Count, Avg, Sum

Write and execute a SQL query to find the minimum, maximum, count, average, and sum of release years in the Netflix dataset.

In [11]:
query ='''SELECT MIN(release_year), MAX(release_year), COUNT(release_year),
AVG(release_year), SUM(release_year) FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

,MIN(release_year),MAX(release_year),COUNT(release_year),AVG(release_year),SUM(release_year)
0,1925,2021,8807,2014.180198,17738885

. Query 8: Like

Write and execute a SQL query to find countries that match specific patterns.

In [12]:
query='''SELECT DISTINCT country FROM netflix WHERE country LIKE '%States%' '''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                                             country
0                                      United States
1  United States, Ghana, Burkina Faso, United Kin...
2                       United States, India, France
3                       China, Canada, United States
4                 South Africa, United States, Japan

 Query 9: In

Write and execute a SQL query to select records where the country is in a specific list.

In [13]:
query='''SELECT * FROM netflix WHERE country IN ('United States', 'India')'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
2,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,s16,TV Show,Dear White People,None,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
4,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

 Query 10: Between

Write and execute a SQL query to select records where the release year is between 2020 and 2021.

In [14]:
query='''SELECT * FROM netflix WHERE release_year BETWEEN 2020 AND 2021'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,None,None,None,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Query 11: Joins

Write and execute a SQL query to join the Netflix table with itself and select specific columns.

In [15]:
query ='''SELECT * FROM netflix AS n1 JOIN netflix AS n2 ON n1.show_id = n2.show_id'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,...,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,...,Dick Johnson Is Dead,Kirsten Johnson,None,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,...,Blood & Water,None,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,TV-MA,1 Season,...,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",None,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,None,None,None,"September 24, 2021",2021,TV-MA,1 Season,...,Jailbirds New Orleans,None,None,None,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,...,Kota Factory,None,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

Query 12: Unions

Write and execute a SQL query to union two different selections from the Netflix table.

In [16]:
query ='''SELECT title, release_year FROM netflix WHERE release_year =2020
 UNION SELECT title, release_year FROM netflix WHERE release_year =2021  '''
df_sql=pd.read_sql(query, engine)
display(df_sql.head())
print()
display(df_sql.tail())

                 title  release_year
0               #Alive          2020
1  #FriendButMarried 2          2020
2             #blackAF          2020
3     #cats_the_mewvie          2020
4             (Un)Well          2020

                                    title  release_year
1540                                 Zero          2021
1541                           Zero Chill          2021
1542                     Zindagi in Short          2020
1543                              Òlòtūré          2020
1544  ​SAINT SEIYA: Knights of the Zodiac          2020

Query 13: Case Statements

Write and execute a SQL query to use CASE statements for conditional logic.

In [17]:
query = '''SELECT title, release_year,
 CASE
 WHEN release_year > 2015 THEN 'current_movie' ELSE 'old_movie' END AS movie_status FROM netflix;'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                   title  release_year   movie_status
0   Dick Johnson Is Dead          2020  current_movie
1          Blood & Water          2021  current_movie
2              Ganglands          2021  current_movie
3  Jailbirds New Orleans          2021  current_movie
4           Kota Factory          2021  current_movie

Query 14: Sub Queries

Write and execute a SQL query to use a subquery for selection.

In [18]:
query ='''SELECT title, release_year , rating FROM netflix
 WHERE rating IN (SELECT rating FROM netflix WHERE rating = 'PG-13')'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                  title  release_year rating
0  Dick Johnson Is Dead          2020  PG-13
1          The Starling          2021  PG-13
2             Grown Ups          2010  PG-13
3            Dark Skies          2013  PG-13
4              Paranoia          2013  PG-13

 Query 15: Coalesce

Write and execute a SQL query to use COALESCE to handle null values.

In [19]:
query= '''SELECT title, COALESCE(country, 'Unknown') AS country,
 COALESCE(director, 'unknown') AS director
 FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                   title        country         director
0   Dick Johnson Is Dead  United States  Kirsten Johnson
1          Blood & Water   South Africa          unknown
2              Ganglands        Unknown  Julien Leclercq
3  Jailbirds New Orleans        Unknown          unknown
4           Kota Factory          India          unknown

Query 16: Convert

Write and execute a SQL query to convert data types.

In [21]:
query ='''SELECT title, CAST(release_year AS TEXT) AS release_year FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                   title release_year
0   Dick Johnson Is Dead         2020
1          Blood & Water         2021
2              Ganglands         2021
3  Jailbirds New Orleans         2021
4           Kota Factory         2021

 Query 17: Lag/Lead

Write and execute a SQL query to use LAG/LEAD for window functions.

In [26]:
query ='''SELECT title, release_year,
 CAST(LAG(release_year) OVER (ORDER BY release_year) AS INTEGER) AS previous_year,
 CAST(LEAD(release_year) OVER (ORDER BY release_year) AS INTEGER) AS next_year
 FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

,title,release_year,previous_year,next_year
0,Pioneers: First Women Filmmakers*,1925,NaN,1942.0
1,Prelude to War,1942,1925.0,1942.0
2,The Battle of Midway,1942,1942.0,1943.0
3,Undercover: How to Operate Behind Enemy Lines,1943,1942.0,1943.0
4,Why We Fight: The Battle of Russia,1943,1943.0,1943.0

Query 18: Row Number

Write and execute a SQL query to use ROW_NUMBER for window functions.

In [27]:
query ='''SELECT title, release_year,
 ROW_NUMBER() OVER (ORDER BY release_year) AS row_num
 FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                                           title  release_year  row_num
0              Pioneers: First Women Filmmakers*          1925        1
1                                 Prelude to War          1942        2
2                           The Battle of Midway          1942        3
3  Undercover: How to Operate Behind Enemy Lines          1943        4
4             Why We Fight: The Battle of Russia          1943        5

 Query 19: Dense Rank

Write and execute a SQL query to use DENSE_RANK for window functions.

In [28]:
query ='''SELECT title, release_year,
 DENSE_RANK() OVER (ORDER BY release_year) AS dense_rank
 FROM netflix'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                                           title  release_year  dense_rank
0              Pioneers: First Women Filmmakers*          1925           1
1                                 Prelude to War          1942           2
2                           The Battle of Midway          1942           2
3  Undercover: How to Operate Behind Enemy Lines          1943           3
4             Why We Fight: The Battle of Russia          1943           3

Query 20: With

Write and execute a SQL query to use WITH clause for common table expressions (CTE).

In [32]:
query='''WITH current_movies AS (SELECT title, director, release_year
FROM netflix WHERE release_year > 2015)
SELECT * FROM current_movies'''
df_sql=pd.read_sql(query, engine)
df_sql.head()

                   title         director  release_year
0   Dick Johnson Is Dead  Kirsten Johnson          2020
1          Blood & Water             None          2021
2              Ganglands  Julien Leclercq          2021
3  Jailbirds New Orleans             None          2021
4           Kota Factory             None          2021