In [1]:
import pandas as pd
df_crop_yield = pd.read_csv('yield.csv')
df_pesticide= pd.read_csv('pesticides.csv')
df_rainfall = pd.read_csv('rainfall.csv')
df_temperature = pd.read_csv('temp.csv')

In [2]:
df_crop_yield.head(20)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value
0,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1961,1961,hg/ha,14000
1,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1962,1962,hg/ha,14000
2,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1963,1963,hg/ha,14260
3,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1964,1964,hg/ha,14257
4,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1965,1965,hg/ha,14400
5,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1966,1966,hg/ha,14400
6,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1967,1967,hg/ha,14144
7,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1968,1968,hg/ha,17064
8,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1969,1969,hg/ha,17177
9,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1970,1970,hg/ha,14757
10,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1971,1971,hg/ha,13400
11,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1972,1972,hg/ha,15652
12,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1973,1973,hg/ha,16170
13,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1974,1974,hg/ha,16170
14,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1975,1975,hg/ha,16116
15,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1976,1976,hg/ha,16598
16,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1977,1977,hg/ha,15833
17,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1978,1978,hg/ha,16183
18,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1979,1979,hg/ha,16102
19,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1980,1980,hg/ha,16711

In [3]:
print(df_crop_yield['Item'].unique())
df_crop_yield[df_crop_yield['Year'] == 1979]

['Maize' 'Potatoes' 'Rice, paddy' 'Wheat' 'Sorghum' 'Soybeans' 'Cassava'
 'Yams' 'Sweet potatoes' 'Plantains and others']

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value
18,QC,Crops,2,Afghanistan,5419,Yield,56,Maize,1979,1979,hg/ha,16102
74,QC,Crops,2,Afghanistan,5419,Yield,116,Potatoes,1979,1979,hg/ha,143575
130,QC,Crops,2,Afghanistan,5419,Yield,27,"Rice, paddy",1979,1979,hg/ha,21311
186,QC,Crops,2,Afghanistan,5419,Yield,15,Wheat,1979,1979,hg/ha,12317
242,QC,Crops,3,Albania,5419,Yield,56,Maize,1979,1979,hg/ha,37500
...,...,...,...,...,...,...,...,...,...,...,...,...
56455,QC,Crops,181,Zimbabwe,5419,Yield,27,"Rice, paddy",1979,1979,hg/ha,5833
56511,QC,Crops,181,Zimbabwe,5419,Yield,83,Sorghum,1979,1979,hg/ha,5856
56567,QC,Crops,181,Zimbabwe,5419,Yield,236,Soybeans,1979,1979,hg/ha,19672
56623,QC,Crops,181,Zimbabwe,5419,Yield,122,Sweet potatoes,1979,1979,hg/ha,22500
56679,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,1979,1979,hg/ha,43931

In [14]:
df_crop_yield.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56717 entries, 0 to 56716
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Domain Code   56717 non-null  object
 1   Domain        56717 non-null  object
 2   Area Code     56717 non-null  int64
 3   Area          56717 non-null  object
 4   Element Code  56717 non-null  int64
 5   Element       56717 non-null  object
 6   Item Code     56717 non-null  int64
 7   Item          56717 non-null  object
 8   Year Code     56717 non-null  int64
 9   Year          56717 non-null  int64
 10  Unit          56717 non-null  object
 11  Value         56717 non-null  int64
dtypes: int64(6), object(6)
memory usage: 5.2+ MB

In [13]:
df_crop_yield.describe()

,Area Code,Element Code,Item Code,Year Code,Year,Value
count,56717.000000,56717.0,56717.000000,56717.000000,56717.000000,56717.000000
mean,125.650422,5419.0,111.611651,1989.669570,1989.669570,62094.660084
std,75.120195,0.0,101.278435,16.133198,16.133198,67835.932856
min,1.000000,5419.0,15.000000,1961.000000,1961.000000,0.000000
25%,58.000000,5419.0,56.000000,1976.000000,1976.000000,15680.000000
50%,122.000000,5419.0,116.000000,1991.000000,1991.000000,36744.000000
75%,184.000000,5419.0,125.000000,2004.000000,2004.000000,86213.000000
max,351.000000,5419.0,489.000000,2016.000000,2016.000000,1000000.000000

In [9]:
df_crop_yield.isnull().sum()

Domain Code     0
Domain          0
Area Code       0
Area            0
Element Code    0
Element         0
Item Code       0
Item            0
Year Code       0
Year            0
Unit            0
Value           0
dtype: int64

In [10]:
df_crop_yield.duplicated().sum()

np.int64(0)

In [4]:
df_rainfall.head(20)

           Area  Year average_rain_fall_mm_per_year
0   Afghanistan  1985                           327
1   Afghanistan  1986                           327
2   Afghanistan  1987                           327
3   Afghanistan  1989                           327
4   Afghanistan  1990                           327
5   Afghanistan  1991                           327
6   Afghanistan  1992                           327
7   Afghanistan  1993                           327
8   Afghanistan  1994                           327
9   Afghanistan  1995                           327
10  Afghanistan  1996                           327
11  Afghanistan  1997                           327
12  Afghanistan  1998                           327
13  Afghanistan  1999                           327
14  Afghanistan  2000                           327
15  Afghanistan  2001                           327
16  Afghanistan  2002                           327
17  Afghanistan  2004                           327
18  Afghanistan  2005                           327
19  Afghanistan  2006                           327

In [15]:
df_rainfall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0    Area                          6727 non-null   object
 1   Year                           6727 non-null   int64
 2   average_rain_fall_mm_per_year  5953 non-null   object
dtypes: int64(1), object(2)
memory usage: 157.8+ KB

In [16]:
df_rainfall.describe()

              Year
count  6727.000000
mean   2001.354839
std       9.530114
min    1985.000000
25%    1993.000000
50%    2001.000000
75%    2010.000000
max    2017.000000

In [12]:
df_rainfall.duplicated().sum()

np.int64(0)

In [11]:
df_rainfall.isnull().sum()

 Area                              0
Year                               0
average_rain_fall_mm_per_year    774
dtype: int64

In [19]:
df_rainfall=df_rainfall.dropna()

In [23]:
df_rainfall['average_rain_fall_mm_per_year']=pd.to_numeric(df_rainfall['average_rain_fall_mm_per_year'], errors='coerce')
df_rainfall= df_rainfall.dropna(subset =['average_rain_fall_mm_per_year'])

C:\Users\njedr\AppData\Local\Temp\ipykernel_35264\2008421034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rainfall['average_rain_fall_mm_per_year']=pd.to_numeric(df_rainfall['average_rain_fall_mm_per_year'], errors='coerce')

In [24]:
df_rainfall['average_rain_fall_mm_per_year']=df_rainfall['average_rain_fall_mm_per_year'].astype('int64')

In [25]:
df_rainfall.describe()

              Year  average_rain_fall_mm_per_year
count  5947.000000                    5947.000000
mean   2001.365899                    1124.743232
std       9.526335                     786.257365
min    1985.000000                      51.000000
25%    1993.000000                     534.000000
50%    2001.000000                    1010.000000
75%    2010.000000                    1651.000000
max    2017.000000                    3240.000000

In [20]:
df_rainfall.isnull().sum()

 Area                            0
Year                             0
average_rain_fall_mm_per_year    0
dtype: int64

In [5]:
df_temperature.head(20)

    year        country  avg_temp
0   1849  Côte D'Ivoire     25.58
1   1850  Côte D'Ivoire     25.52
2   1851  Côte D'Ivoire     25.67
3   1852  Côte D'Ivoire       NaN
4   1853  Côte D'Ivoire       NaN
5   1854  Côte D'Ivoire       NaN
6   1855  Côte D'Ivoire       NaN
7   1856  Côte D'Ivoire     26.28
8   1857  Côte D'Ivoire     25.17
9   1858  Côte D'Ivoire     25.49
10  1859  Côte D'Ivoire     25.92
11  1860  Côte D'Ivoire     25.46
12  1861  Côte D'Ivoire     25.67
13  1862  Côte D'Ivoire     25.17
14  1863  Côte D'Ivoire       NaN
15  1864  Côte D'Ivoire       NaN
16  1865  Côte D'Ivoire       NaN
17  1866  Côte D'Ivoire       NaN
18  1867  Côte D'Ivoire       NaN
19  1868  Côte D'Ivoire       NaN

In [26]:
df_temperature.describe()

               year      avg_temp
count  71311.000000  68764.000000
mean    1905.799007     16.183876
std       67.102099      7.592960
min     1743.000000    -14.350000
25%     1858.000000      9.750000
50%     1910.000000     16.140000
75%     1962.000000     23.762500
max     2013.000000     30.730000

In [6]:
df_pesticide.head(20)

,Domain,Area,Element,Item,Year,Unit,Value
0,Pesticides Use,Albania,Use,Pesticides (total),1990,tonnes of active ingredients,121.00
1,Pesticides Use,Albania,Use,Pesticides (total),1991,tonnes of active ingredients,121.00
2,Pesticides Use,Albania,Use,Pesticides (total),1992,tonnes of active ingredients,121.00
3,Pesticides Use,Albania,Use,Pesticides (total),1993,tonnes of active ingredients,121.00
4,Pesticides Use,Albania,Use,Pesticides (total),1994,tonnes of active ingredients,201.00
5,Pesticides Use,Albania,Use,Pesticides (total),1995,tonnes of active ingredients,251.00
6,Pesticides Use,Albania,Use,Pesticides (total),1996,tonnes of active ingredients,313.96
7,Pesticides Use,Albania,Use,Pesticides (total),1997,tonnes of active ingredients,376.93
8,Pesticides Use,Albania,Use,Pesticides (total),1998,tonnes of active ingredients,439.89
9,Pesticides Use,Albania,Use,Pesticides (total),1999,tonnes of active ingredients,502.86
10,Pesticides Use,Albania,Use,Pesticides (total),2000,tonnes of active ingredients,565.82
11,Pesticides Use,Albania,Use,Pesticides (total),2001,tonnes of active ingredients,628.79
12,Pesticides Use,Albania,Use,Pesticides (total),2002,tonnes of active ingredients,691.75
13,Pesticides Use,Albania,Use,Pesticides (total),2003,tonnes of active ingredients,754.71
14,Pesticides Use,Albania,Use,Pesticides (total),2004,tonnes of active ingredients,817.68
15,Pesticides Use,Albania,Use,Pesticides (total),2005,tonnes of active ingredients,880.64
16,Pesticides Use,Albania,Use,Pesticides (total),2006,tonnes of active ingredients,943.61
17,Pesticides Use,Albania,Use,Pesticides (total),2007,tonnes of active ingredients,1006.57
18,Pesticides Use,Albania,Use,Pesticides (total),2008,tonnes of active ingredients,1069.54
19,Pesticides Use,Albania,Use,Pesticides (total),2009,tonnes of active ingredients,1132.50

In [7]:
df_crop_yield.tail(20)

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value
56697,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,1997,1997,hg/ha,56000
56698,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,1998,1998,hg/ha,55000
56699,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,1999,1999,hg/ha,55000
56700,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2000,2000,hg/ha,54000
56701,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2001,2001,hg/ha,53000
56702,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2002,2002,hg/ha,50000
56703,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2003,2003,hg/ha,30000
56704,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2004,2004,hg/ha,35000
56705,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2005,2005,hg/ha,35000
56706,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2006,2006,hg/ha,36000
56707,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2007,2007,hg/ha,29998
56708,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2008,2008,hg/ha,30097
56709,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2009,2009,hg/ha,30000
56710,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2010,2010,hg/ha,27681
56711,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2011,2011,hg/ha,26274
56712,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2012,2012,hg/ha,24420
56713,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2013,2013,hg/ha,22888
56714,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2014,2014,hg/ha,21357
56715,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2015,2015,hg/ha,19826
56716,QC,Crops,181,Zimbabwe,5419,Yield,15,Wheat,2016,2016,hg/ha,18294

In [8]:
print(f'yield shape: {df_crop_yield.shape[0]}')
print(f'pesticide shape: {df_pesticide.shape[0]}')
print(f'rainfall shape: {df_rainfall.shape[0]}')    
print(f'temperature shape: {df_temperature.shape[0]}')

yield shape: 56717
pesticide shape: 4349
rainfall shape: 6727
temperature shape: 71311